apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-helm-example
  labels:
    app.kubernetes.io/instance: go-app
    app.kubernetes.io/name: helm-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: go-app
      app.kubernetes.io/name: helm-example
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: go-app
        app.kubernetes.io/name: helm-example
    spec:
      containers:
        - name: helm-example
          image: franciscocodefresh/go-app:argocd-pipeline-9ncfz
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources: {}
