apiVersion: v1
kind: Service
metadata:
  name: go-app-helm-example
  labels:
    app.kubernetes.io/instance: go-app
    app.kubernetes.io/name: helm-example
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: go-app
    app.kubernetes.io/name: helm-example
